name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: rust toolchain 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: build
        run: |
          ls -al 
          cd rusts_algo
          cargo build --verbose

      - name: lint
        run: |
          ls -al
          cd rusts_algo
          echo 'not run anything yet but do later' 

      - name: Run tests
        run: |
          ls -al
          cd rusts_algo
          cargo test --verbose


